route:
#  receiver: 'web.hook'
#  repeat_interval: 2m
  group_by: [ 'alertname', 'host', 'instance', 'service' ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: 'telegram-webhook'
# route child
  routes:
  - receiver: 'telegram-webhook'
    repeat_interval: 2m
    match:
        severity: critical|warning  
  
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'host', 'instance', 'service']

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'your_mail@gmail.com'
        auth_password: ""
        from: 'your_mail@gmail.com'
        to: 'some_mail@gmail.com'
#
  - name: 'telegram-webhook'
    webhook_configs:
      - url: 'http://prometheus-bot:9087/alert/-668754451'
