global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - ./rules/*.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    - node-exporter:9100
- job_name: webserver
  static_configs:
#    - targets: ['172.16.3.233:9100']
#      labels:
#        alias: ubuntu-host
#    - targets: ['172.16.3.234:9100']
#      labels:
#        alias: centos-host
#    - targets: ['172.16.3.236:9100']
#      labels:
#        alias: wordpress-host

- job_name: blackbox # To get metrics about the exporter itself
  metrics_path: /metrics
  static_configs:
    - targets:
      - 172.16.3.232:9115

- job_name: 'blackbox-http'
  metrics_path: /probe
  params:
    module: [http_2xx]  # Look for a HTTP 200 response.
  static_configs:
    - targets:
      #- http://prometheus.io    # Target to probe with http.
      - https://crm3.edupia.edu.vn   # Target to probe with https.
      - https://bitrix24.edupia.edu.vn
      #- 172.16.3.236:8080
      #- http://shophatde.com/
      #- http://example.com:8080 # Target to probe with http on port 8080.
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 172.16.3.232:9115  # The blackbox exporter's real hostname:port.
