telegram_token: "5705679733:AAF2DUdS0Jt7hM_9HkIILOZ9Qh45-1O3HnM"
template_path: "/etc/telegrambot/template.tmpl"
time_zone: "Asia/Ho_Chi_Minh"
split_token: "|"
time_outdata: "02/01/2006 15:04:05"
split_msg_byte: 10000
